[package]
name = "vplot"
version = "0.1.0"
authors = ["Spencer Nystrom <nystromdev@gmail.com>"]
edition = "2018"

[dependencies]
csv = "*"
bio = "*"
rust-htslib = {version = "*", default-features = false}
structopt = "*"
ndarray = "0.13.1"
ndarray-csv = "*"
