[package]
name = "vplot"
version = "0.2.2"
authors = ["Spencer Nystrom <nystromdev@gmail.com>"]
edition = "2018"

[dependencies]
csv = "*"
bio = "*"
rust-htslib = {version = "0.32", default-features = false}
structopt = "*"
ndarray = "0.13.1"
ndarray-csv = "*"
