[package]
name = "vplot"
version = "0.3.1"
authors = ["Spencer Nystrom <nystromdev@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
bio = "0.32.0"
rust-htslib = {version = "0.32", default-features = false}
structopt = "*"
ndarray = "0.13.1"
ndarray-csv = "0.4.1"
